server:
  port: 8801

xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8090/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      address: ''
      ip: ''
      port: 8099
      logpath: /logs/xxl-job/jobhandler
      logretentiondays: 3

spring:
  application:
    name: redis-test
  cloud:
    nacos:
      username: nacos
      password: O9MeXU0SExEx5jp0KE4U
      discovery:
        server-addr: 119.3.216.80:8848,121.36.35.198:8848,119.3.214.140:8848
        namespace: 5d2b1d22-a8d1-4005-9a84-8818228d2b7f
        watch-delay: 15
  redis:
    cluster:
      nodes:
        - 47.94.237.238:7001
        - 47.94.237.238:7002
        - 47.94.237.238:7003
        - 47.94.237.238:7004
        - 47.94.237.238:7005
        - 47.94.237.238:7006
    password: liuze0118
  #  redis:
#    cluster:
#      nodes: 47.94.237.238:7001,47.94.237.238:7002,47.94.237.238:7003,47.94.237.238:7004,47.94.237.238:7005,47.94.237.238:7006
#    password: liuze0118
  elasticsearch:
    rest:
      uris: http://47.94.237.238:9200
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://47.94.237.238:3306/my_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: liuze0118
  aop:
    proxy-target-class: false
  data:
    mongodb:
      uri: mongodb://egd_hcid_new:adWRvM7hBfVYYH71W37T+@dev.dbaddr2.jiankangyouyi.com:8509/ego_gw_db?connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=10&maxIdleTimeMS=900000
#      uri: mongodb://jy_self:G20MaW1ct%5EeBC8Pfg2QN@prod.dbaddr5.jiankangyouyi.com:8635/jy_db?connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=10&maxIdleTimeMS=900000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.lz.redis.demo.config

license:
  subject: jiangkanyouyi
  publicAlias: publicCert
  storePass: liu123
  licensePath: license.lic
  publicKeysStorePath: publicCerts.store

management:
  endpoints:
    web:
      exposure:
        include: self-registry
      base-path: /actuator
  endpoint:
    self-registry:
      enable: true

java:
  home: ${JAVA_HOME}

mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=