server:
  port: 8801

xxl:
  job:
    accessToken:
    admin:
      addresses: xxxx
    executor:
      appname: xxl-job-executor-sample
      address: ''
      ip: ''
      port: 8099
      logpath: /logs/xxl-job/jobhandler
      logretentiondays: 3

spring:
  application:
    name: redis-test
  cloud:
    nacos:
      username: nacos
      password: xxxx
      discovery:
        server-addr: 119.3.216.80:8848,121.36.35.198:8848,119.3.214.140:8848
        namespace: 5d2b1d22-a8d1-4005-9a84-8818228d2b7f
        watch-delay: 15
  redis:
    cluster:
      uri: xxxx
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.lz.redis.demo.config

license:
  subject: jiangkanyouyi
  publicAlias: publicCert
  storePass: liu123
  licensePath: license.lic
  publicKeysStorePath: publicCerts.store

management:
  endpoints:
    web:
      exposure:
        include: self-registry
      base-path: /actuator
  endpoint:
    self-registry:
      enable: true

java:
  home: ${JAVA_HOME}

logging:
  config: classpath:log4j2-dev.xml
  level:
    com: trace
  file:
    path: ./log


mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=

uploadurl: xxxx

oss:
  secretId: xxxx
  secretKey: xxxx
  bucket: xxx